version: '{build}'

image: Visual Studio 2019

environment:
  LIBRARY_VERSION: '2.17.5'
  SONAR_LOGIN:
    secure: JNopXLZtkO5PD8yEj2+W1BZnbhq9oegXmTFgvVWQw67z5PtWwd+ngjv5O7xFetCZ

test: off

build_script:
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet test

artifacts:
  - path: '**\*.nupkg'
